artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://image-recipe-generator.s3.ap-south-1.amazonaws.com/FOOD.zip"
  local_data_file: artifacts/data_ingestion/FOOD.zip  
  unzip_dir: artifacts/data/raw  
  raw_images_dir: artifacts/data/raw/images
  raw_recipes_dir: artifacts/data/raw/recipes

image_processing: 
  root_dir: artifacts
  processed_dir: artifacts/data/processed/images
  image_size: [224, 224]
  normalize: true
  augmentation: false

feature_extraction:
  root_dir: artifacts/feature_extraction
  processed_images_dir: artifacts/data/processed/images
  features_dir: artifacts/feature_extraction/features
  model_name: "resnet50"
  batch_size: 32
  use_gpu: true
  pretrained: true
  freeze_weights: true