name: Trigger Jenkins Job

on:
  workflow_dispatch:

jobs:
   trigger:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v0.1.3
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: ${{ secrets.JOBS }}